/**
 * SPEC-ROL-001 — Rollout UI copy (normative operator-facing Chinese)
 */

export const rolloutUi = {
  pageTitle: "Rollout 投影",
  pageSubtitle: "将 Discovery 接受的 Story / Scene 候选持久化并关联 Runtime Scene",
  importFromDiscovery: "从 Discovery 导入",
  importEmpty: "未找到 Discovery 会话中的已接受 staging",
  importSuccess: "已导入 staging 到 Rollout 队列",
  storyStagingTitle: "待持久化 Story 单元",
  sceneStagingTitle: "待投影 Scene 候选",
  approvedStoryTitle: "已批准 Story 单元",
  runtimeScenesTitle: "Runtime Scene",
  noRuntimeScenes: "暂无 Runtime Scene",
  goEditScene: "编辑 Scene",
  goScenesList: "Scene 列表",
  sceneRolloutProjection: "Rollout 投影",
  sceneCatalogOrigin: "目录 / 其他途径创建",
  sceneLinkCount: (count: number) =>
    count > 0 ? `${count} 个 Story 关联` : "无 Story 关联",
  linksTitle: "Story ↔ Scene 关联",
  noStoryStaging: "暂无待持久化 Story staging",
  noSceneStaging: "暂无待投影 Scene staging",
  noStoryUnits: "暂无已批准 Story 单元",
  noLinks: "暂无 Story ↔ Scene 关联",
  persistStory: "持久化 Story 单元",
  projectCreate: "创建 Scene 并投影",
  projectLink: "关联已有 Scene",
  dismissStaging: "移出队列",
  restoreStaging: "恢复到待处理",
  dismissedStoryTitle: "已移出队列的 Story staging",
  dismissedSceneTitle: "已移出队列的 Scene staging",
  noDismissedStoryStaging: "暂无已移出的 Story staging",
  noDismissedSceneStaging: "暂无已移出的 Scene staging",
  projectedSceneTitle: "已投影 Scene 候选",
  noProjectedScenes: "暂无已投影 Scene 候选",
  unprojectScene: "取消投影",
  confirmUnprojectScene:
    "确定取消投影？create 模式会删除新建的 Runtime Scene；staging 将回到「待投影 Scene 候选」。",
  createLink: "创建关联",
  unlink: "解除关联",
  archive: "归档",
  editStoryUnit: "编辑",
  editStoryUnitTitle: "编辑 Story 单元",
  editStoryUnitDesc: "修改标题、摘要与边界提示；保存后立即写入数据库。",
  editStoryUnitTitleLabel: "标题",
  editStoryUnitSummaryLabel: "摘要",
  editStoryUnitBoundaryLabel: "边界提示（可选）",
  saveStoryUnit: "保存",
  unpersistStory: "取消持久化",
  confirmUnpersistStory:
    "确定取消持久化？将从数据库移除，并重新出现在「待持久化 Story 单元」列表。",
  unpersistStoryBlocked: "存在 Scene 关联，请先解除全部关联后再取消持久化",
  linkStoryUnit: "Story 单元",
  linkScene: "Scene",
  selectScene: "选择 Scene",
  optionalLinkStory: "可选：关联到 Story 单元",
  confirmCreateScene: "确认创建 Scene",
  confirmCreateSceneDesc:
    "将按 staging 字段创建 Runtime Scene。创建前请确认字段映射正确。",
  loading: "加载中…",
  actionError: "操作失败",
  fieldErrorsLabel: "字段错误",
  refresh: "刷新",
  goDiscovery: "前往 Discovery",
  tabPending: "待处理",
  tabDismissed: "已移出",
  tabStoryUnits: "Story 单元",
  tabRuntimeScenes: "Runtime Scene",
  tabLinks: "关联",
  workspaceTitle: "Rollout 工作台",
  workspaceDescription: "Discovery 采纳 → 持久化 Story → 投影 Scene → 建立关联",
  flowHintPending: "持久化 Story 后在「Story 单元」查看；投影 Scene 后在「Runtime Scene」查看",
  flowHintPendingEmpty: "待处理队列已清空",
  flowHintStoryUnits: "持久化完成后，前往「Runtime Scene」投影场景候选",
  flowHintRuntimeScenes: "Scene 投影完成后，前往「关联」步骤建立 Story ↔ Scene 映射",
  flowHintLinks: "关联建立完成 — 整个 Rollout 投影流程结束",
  nextStepStoryUnits: "Story 单元",
  nextStepRuntimeScenes: "Runtime Scene",
  nextStepLinks: "建立关联",
  nextStepDiscovery: "返回 Discovery 审核更多",
  pipelineFromDiscovery: "Discovery 采纳",
} as const;
