/**
 * SPEC-ROL-001 — Rollout UI copy (normative operator-facing Chinese)
 * SPEC-VDC-001 Phase 4b — strings sourced from lib/locale
 */

import { messages } from "@/lib/locale";

const m = messages.rollout;
const d = messages.domain;

export const rolloutUi = {
  pageTitle: m.pageTitle,
  pageSubtitle: m.pageSubtitle,
  importFromDiscovery: m.importFromDiscovery,
  importEmpty: m.importEmpty,
  importSuccess: m.importSuccess,
  storyStagingTitle: m.storyStagingTitle,
  sceneStagingTitle: m.stagingTitle,
  approvedStoryTitle: m.approvedStoryTitle,
  runtimeScenesTitle: m.runtimeTitle,
  noRuntimeScenes: m.noRuntime,
  projectedOrphanTitle: m.projectedOrphanTitle,
  projectedOrphanHint: m.projectedOrphanHint,
  projectedParentStory: m.projectedParentStory,
  goEditScene: m.editItem,
  goScenesList: m.listItems,
  sceneRolloutProjection: m.projectionRecord,
  sceneCatalogOrigin: m.catalogOrigin,
  sceneLinkCount: m.storyLinkCount,
  linksTitle: m.linksTitle,
  noStoryStaging: m.noStoryStaging,
  writePreviewHint: m.writePreviewHint,
  noSceneStaging: m.noStaging,
  noStoryUnits: m.noStoryUnits,
  noLinks: m.noLinks,
  persistStory: m.persistStory,
  projectCreate: m.projectCreate,
  projectLink: m.projectLink,
  dismissStaging: m.dismissStaging,
  restoreStaging: m.restoreStaging,
  dismissedStoryTitle: m.dismissedStoryTitle,
  dismissedSceneTitle: m.dismissedTitle,
  noDismissedStoryStaging: m.noDismissedStoryStaging,
  noDismissedSceneStaging: m.noDismissed,
  projectedSceneTitle: m.projectedTitle,
  noProjectedScenes: m.noProjected,
  unprojectScene: m.unproject,
  confirmUnprojectScene: m.confirmUnproject,
  createLink: m.createLink,
  unlink: m.unlink,
  archive: m.archive,
  editStoryUnit: m.editStoryUnit,
  editStoryUnitTitle: m.editStoryUnitTitle,
  editStoryUnitDesc: m.editStoryUnitDesc,
  editStoryUnitTitleLabel: m.editStoryUnitTitleLabel,
  editStoryUnitSummaryLabel: m.editStoryUnitSummaryLabel,
  editStoryUnitBoundaryLabel: m.editStoryUnitBoundaryLabel,
  saveStoryUnit: m.saveStoryUnit,
  unpersistStory: m.unpersistStory,
  confirmUnpersistStory: m.confirmUnpersistStory,
  unpersistStoryBlocked: m.associationBlocked,
  linkStoryUnit: m.linkStoryUnit,
  linkScene: m.linkItem,
  selectScene: m.selectItem,
  optionalLinkStory: m.optionalLinkStory,
  confirmCreateScene: m.confirmCreate,
  confirmCreateSceneDesc: m.confirmCreateDesc,
  projectionValidationTitle: m.projectionValidationTitle,
  projectionValidationParentMissing: m.projectionValidationParentMissing,
  loading: m.loading,
  actionError: m.actionError,
  fieldErrorsLabel: m.fieldErrorsLabel,
  refresh: m.refresh,
  goDiscovery: m.goDiscovery,
  tabPending: m.tabPending,
  tabDismissed: m.tabDismissed,
  tabStoryUnits: m.tabStoryUnits,
  tabPersisted: m.tabPersisted,
  tabRuntimeScenes: m.runtimeTab,
  tabLinks: m.tabLinks,
  workspaceTitle: m.workspaceTitle,
  workspaceDescription: m.workspaceDescription,
  flowHintPending: m.flowHintPending,
  flowHintPendingEmpty: m.flowHintPendingEmpty,
  flowHintStoryUnits: m.flowHintStoryUnitsProjection,
  flowHintRuntimeScenes: m.flowHintRuntimeScenes,
  flowHintLinks: m.flowHintLinks,
  nextStepStoryUnits: m.nextStepStoryUnits,
  nextStepRuntimeScenes: m.nextStep,
  nextStepLinks: m.nextStepLinks,
  nextStepDiscovery: m.nextStepDiscovery,
  pipelineFromDiscovery: m.pipelineFromDiscovery,
  entitySectionDeferred: m.entitySectionDeferred,
  storyRelatedFromFrames: m.storyRelatedFromFrames,
  storyRelatedFromFramesEmpty: m.storyRelatedFromFramesEmpty,
  openReaderVerify: m.openReaderVerify,
} as const;

/** Re-export domain label for dynamic tab descriptions in RolloutPanel */
export const rolloutDomainLabels = d;
